---
title: "PCA iterative + PCA"
author: "ALS"
date: "17/10/2022"
---
```{r include = FALSE}
library(Factoshiny)
library(dplyr)
library(tidyr)
library(readr)
library(stringr)
library(missMDA)
library(sp)
setwd("~/Documents/Perceptual_Space_ALS/")
path1 <- ("df_pca/")
```

Compute PCA + dispersion + save data

```{r include = FALSE}

all_fnames <- list.files(path = path1, pattern = "scaled.csv")

for (i in 1:length(all_fnames)){
  
  filename <- paste(path1, all_fnames[i], sep = "")
  fname2 <- str_replace(filename, "_scaled", "_ALLDATA")

  essai_pca <- read_csv(filename, show_col_types = FALSE)

  if (any(is.na(essai_pca)) == TRUE){
    comp <- imputePCA(essai_pca[4:7], ncp = 2, scale = TRUE)
    df_new <- cbind(essai_pca[1:3], comp$completeObs)
    res.PCA<-PCA(df_new[3:7], quali.sup=c(1), graph = FALSE)
    fname2 <- str_replace(filename, "_scaled", "_ALLDATA")
    write.csv(df_new, fname2)
    }
  
  else{
    res.PCA<-PCA(essai_pca[3:7],  quali.sup=c(1), graph = FALSE)
    write.csv(essai_pca, fname2)
    }
  
  pca_df <- cbind(essai_pca[1:3], res.PCA$ind)
  sum_df <- as.data.frame(res.PCA$eig) #summary(res.PCA)
  
  #Find the subset of points and plot the convex hull
  hpts <- chull(pca_df[4:5])
  hpts <- c(hpts, hpts[1])
  pts <- pca_df[hpts,]

  #Create polygon & compute surface
  chull.poly <- Polygon(pts[4:5], hole=F)
  chull.area <- chull.poly@area
  sum_df['surf poly'] <- chull.area #summary(res.PCA)

  #Compute mean dist and circle area
  radius <- mean(pca_df$dist)
  x0 <- mean(pca_df$coord.Dim.1)
  y0 <- mean(pca_df$coord.Dim.2)
  sum_df %>% add_column(c_x0 = x0, c_y0 = y0, c_r = radius)
  sum_df['surf circle'] <- pi*(radius^2)
  sum_df['x0'] <- x0
  sum_df['y0'] <- y0
  sum_df['radius'] <- radius

  fname3 <- str_replace(filename, "_scaled", "_PCA")
  fname4 <- str_replace(filename, "_scaled", "_PCA_sum")
  
  write.csv(pca_df, fname3)
  write.csv(sum_df, fname4)
  }
```
